kind = "web"
previewPath = "/"
title = "Aisync"
version = "1.0.0"
id = "artifacts/aisync"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23763

[services.development]
run = "pnpm --filter @workspace/aisync run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/aisync", "run", "build" ]
publicDir = "artifacts/aisync/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23763"
BASE_PATH = "/"
